routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/add-to-cart/{product}', 'CartController@add')->name('cart.add')->middleware('auth');
Route::get('/cart', 'CartController@index')->name('cart.index')->middleware('auth');
Route::get('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy')->middleware('auth');
Route::get('/cart/update/{itemId}', 'CartController@update')->name('cart.update')->middleware('auth');
Route::get('/cart/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('auth');

Route::resource('orders', 'OrderController')->middleware('auth');

Route::resource('shops', 'ShopController')->middleware('auth');

Route::get('paypal/checkout/{order}', 'PayPalController@getExpressCheckout')->name('paypal.checkout');
Route::get('paypal/checkout-success/{order}', 'PayPalController@getExpressCheckoutSuccess')->name('paypal.success');
Route::get('paypal/checkout-cancel', 'PayPalController@cancelPage')->name('paypal.cancel');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class CartController extends Controller
{
    public function add(Product $product)
    {
        // dd($product);

        //add to cart
        \Cart::session(auth()->id())->add(array(
            'id' => $product->id,
            'name' => $product->name,
            'price' => $product->price,
            'quantity' => 1,
            'attributes' => array(),
            'associatedModel' => $product
        ));

        return redirect()->route('cart.index');
    }

    public function index()
    {
        $cartItems = \Cart::session(auth()->id())->getContent();
        return view('cart.index', compact('cartItems'));
    }

    public function destroy($itemId)
    {
        \Cart::session(auth()->id())->remove($itemId);

        return back();
    }

    public function update($rowId)
    {
        \Cart::session(auth()->id())->update($rowId, [
            'quantity'=> array(
                'relative' => false,
                'value' => request('quantity')
            )
        ]);

        return back();
    }

    public function checkout()
    {
        return view('cart.checkout');
    }
}

resources/views/cart/checkout.blade.php
@extends('layouts.app')

@section('content')

<h2>Checkout</h2>

<h3>Shipping Information</h3>

<form action="{{ route('orders.store') }}" method="post">
    @csrf

    <div class="form-group">
        <label for="">Full Name</label>
        <input type="text" name="shipping_fullname" id="" class="form-control">
    </div>

    <div class="form-group">
        <label for="">State</label>
        <input type="text" name="shipping_state" class="form-control">
    </div>

    <div class="form-group">
        <label for="">City</label>
        <input type="text" name="shipping_city" class="form-control">
    </div>

    <div class="form-group">
        <label for="">Zip</label>
        <input type="text" name="shipping_zipcode" class="form-control">
    </div>

    <div class="form-group">
        <label for="">Full Address</label>
        <input type="text" name="shipping_address" class="form-control">
    </div>

    <div class="form-group">
        <label for="">Mobile</label>
        <input type="text" name="shipping_phone" class="form-control">
    </div>

    <h4>Payment Option</h4>

    <div class="form-check">
        <label class="form-check-label">
        <input type="radio" class="form-check-input" name="payment_method" id="" value="cash_on_delivery" checked>
        Cash on delivery
      </label>
    </div>

    <div class="form-check">
        <label class="form-check-label">
        <input type="radio" class="form-check-input" name="payment_method" id="" value="paypal">
        Paypal
      </label>
    </div>

    <button type="submit" class="btn btn-primary mt-3">Place Order</button>

</form>


@endsection

resources/views/cart/index.blade.php
@extends('layouts.app')

@section('content')

    <h2>Your cart</h2>

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>SubTotal</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($cartItems as $item)

                <tr>
                    <td scope="row">
                        {{ $item->name }}
                    </td>
                    <td>
                        {{ $item->price }}
                    </td>
                    <td>
                        <form action="{{ route('cart.update', $item->id) }}">
                            <input name="quantity" type="number" value="{{ $item->quantity }}">
                            <input type="submit" value="save">
                        </form>
                    </td>
                    <td>
                        {{ Cart::session(auth()->id())->get($item->id)->getPriceSum() }}
                    </td>
                    <td>
                        <a href="{{ route('cart.destroy', $item->id) }}">Delete</a>
                    </td>
                </tr>

                @endforeach

           </tbody>
       </table>

       <h3>
           Total Price: ${{ \Cart::session(auth()->id())->getTotal() }}
       </h3>

    <a href="{{ route('cart.checkout') }}" class="btn btn-primary" role="button">
           Proceed to checkout
       </a>

@endsection